wts2-902/fl2-344/Strain Curator update load

diff --git a/bin/runStrainQC b/bin/runStrainQC
--- a/bin/runStrainQC
+++ b/bin/runStrainQC
@@ -15,6 +15,7 @@ then
 fi
 
 . ${MGICONFIG}/master.config.sh
+CONFIG=${STRAINCURATORLOAD}/straincurator.config
 
 usage ()
 {
@@ -44,6 +45,17 @@ then
     fi
 else
     usage
+fi
+
+#
+# Make sure the configuration file exists and source it.
+#
+if [ -f ${CONFIG} ]
+then
+    . ${CONFIG}
+else
+    echo "Missing configuration file: ${CONFIG}"
+    exit 1
 fi
 
 #
